name: Docker Release
"on":
  push:
    branches:
      - main
  workflow_dispatch: null
permissions:
  contents: write
  id-token: write
jobs:
  release:
    uses: udx/reusable-workflows/.github/workflows/docker-ops.yml@master
    with:
      image_name: ${{ vars.IMAGE_NAME }}
      gcp_region: ${{ vars.GCP_REGION }}
      gcp_project_id: ${{ vars.GCP_PROJECT_ID }}
      gcp_repo: ${{ vars.GCP_REPO }}
      gcp_workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      gcp_service_account: ${{ vars.GCP_SERVICE_ACCOUNT }}
      release_branch: latest
      dockerfile_path: ./Dockerfile
      build_platforms: linux/amd64,linux/arm64
      version_config_path: ci/git-version.yml
      build_args: ""
      enable_security_scan: "true"
      enable_security_upload: "true"
      enable_sbom: "true"
