name: Docker Release Example

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  # ===========================================================================
  # Example 1: Minimal - GitHub Release Only
  # USE CASE: Build and scan Docker image, create GitHub release with SBOM
  # REQUIRED: Only image_name
  # PUBLISHES TO: GitHub Releases only (no external registries)

  # minimal:
  #   uses: udx/reusable-workflows/.github/workflows/docker-ops.yml@master
  #   with:
  #     image_name: my-app

  # ===========================================================================
  # Example 2: Docker Hub Publishing
  # USE CASE: Publish to Docker Hub with version and latest tags
  # REQUIRED: image_name, docker_login, docker_org, docker_repo, docker_token secret
  # PUBLISHES TO: Docker Hub + GitHub Releases

  # docker-hub:
  #   uses: udx/reusable-workflows/.github/workflows/docker-ops.yml@master
  #   with:
  #     image_name: my-app
  #     docker_login: myusername
  #     docker_org: myorg
  #     docker_repo: my-app
  #   secrets:
  #     docker_token: ${{ secrets.DOCKER_TOKEN }}

  # ===========================================================================
  # Example 3: Multi-Registry (Docker Hub + GCP + ACR + Slack)
  # USE CASE: Enterprise deployment to multiple cloud registries with notifications
  # REQUIRED: All inputs for each target registry (see Dependency Matrix in docs/docker-ops.md)
  # PUBLISHES TO: Docker Hub + GCP Artifact Registry + Azure Container Registry + GitHub Releases

  multi-registry:
    permissions:
      id-token: write # Required for GCP and Azure OIDC authentication
      contents: write # Required for GitHub releases
    uses: udx/reusable-workflows/.github/workflows/docker-ops.yml@master
    with:
      image_name: my-app
      release_branch: main

      # Docker Hub Configuration
      # Required: docker_login, docker_org, docker_repo, docker_token secret
      docker_login: ${{ vars.DOCKER_USERNAME }}
      docker_org: myorg
      docker_repo: my-app

      # GCP Artifact Registry (Workload Identity Federation - Keyless Auth)
      # Required: All 5 inputs below
      # Setup: See docs/docker-ops.md "GCP Workload Identity Federation Setup"
      gcp_region: us-central1
      gcp_project_id: my-gcp-project
      gcp_repo: docker-images
      gcp_workload_identity_provider: projects/123456789/locations/global/workloadIdentityPools/github/providers/github-provider
      gcp_service_account: github-actions@my-gcp-project.iam.gserviceaccount.com

      # Azure Container Registry (OIDC - Keyless Auth)
      # Required: All 5 inputs below
      # Setup: See docs/docker-ops.md "Azure OIDC Setup"
      # Note: IDs below are fake examples - replace with your actual Azure values
      acr_registry: myregistry.azurecr.io
      acr_repository: my-app
      azure_client_id: 12345678-90ab-cdef-1234-567890abcdef
      azure_tenant_id: 87654321-fedc-ba09-8765-4321fedcba09
      azure_subscription_id: a1b2c3d4-e5f6-7890-abcd-ef1234567890

      # Optional: Custom build settings
      dockerfile_path: ./Dockerfile
      build_platforms: linux/amd64,linux/arm64
      # Build args support placeholders: {{version}} = release version, {{branch}} = branch name
      build_args: APP_VERSION={{version}},BUILD_DATE={{branch}},ENV=production

    secrets:
      docker_token: ${{ secrets.DOCKER_TOKEN }}
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}

# Full Documentation:
#   - See docs/docker-ops.md for complete setup guides, troubleshooting, and best practices
