name: Docker Release Example

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  # ===========================================================================
  # Example 1: Minimal - GitHub Release Only
  # ===========================================================================
  # USE CASE: Build and scan Docker image, create GitHub release with SBOM
  # REQUIRED: Only image_name
  # PUBLISHES TO: GitHub Releases only (no external registries)
  # AI NOTE: Use this when you only need CI/CD without registry publishing

  # minimal:
  #   uses: udx/reusable-workflows/.github/workflows/docker-ops.yml@master
  #   with:
  #     image_name: my-app

  # ===========================================================================
  # Example 2: Docker Hub Publishing
  # ===========================================================================
  # USE CASE: Publish to Docker Hub with version and latest tags
  # REQUIRED: image_name, docker_login, docker_org, docker_repo, docker_token secret
  # PUBLISHES TO: Docker Hub + GitHub Releases
  # AI NOTE: Check Dependency Matrix in docs/docker-ops.md for all mandatory inputs

  # docker-hub:
  #   uses: udx/reusable-workflows/.github/workflows/docker-ops.yml@master
  #   with:
  #     image_name: my-app
  #     docker_login: myusername
  #     docker_org: myorg
  #     docker_repo: my-app
  #   secrets:
  #     docker_token: ${{ secrets.DOCKER_TOKEN }}

  # ===========================================================================
  # Example 3: Multi-Registry (Docker Hub + GCP + ACR + Slack)
  # ===========================================================================
  # USE CASE: Enterprise deployment to multiple cloud registries with notifications
  # REQUIRED: All inputs for each target registry (see Dependency Matrix in docs/docker-ops.md)
  # PUBLISHES TO: Docker Hub + GCP Artifact Registry + Azure Container Registry + GitHub Releases
  # SECURITY: Requires id-token: write permission for GCP and ACR OIDC authentication
  # AI NOTE: All IDs below are fake examples - replace with your actual values

  multi-registry:
    permissions:
      id-token: write # Required for GCP and Azure OIDC authentication
      contents: write # Required for GitHub releases
    uses: udx/reusable-workflows/.github/workflows/docker-ops.yml@master
    with:
      image_name: my-app
      release_branch: main

      # Docker Hub Configuration
      # Required: docker_login, docker_org, docker_repo, docker_token secret
      docker_login: ${{ vars.DOCKER_USERNAME }}
      docker_org: myorg
      docker_repo: my-app

      # GCP Artifact Registry (Workload Identity Federation - Keyless Auth)
      # Required: All 5 inputs below
      # Setup: See docs/docker-ops.md "GCP Workload Identity Federation Setup"
      gcp_region: us-central1
      gcp_project_id: my-gcp-project
      gcp_repo: docker-images
      gcp_workload_identity_provider: projects/123456789/locations/global/workloadIdentityPools/github/providers/github-provider
      gcp_service_account: github-actions@my-gcp-project.iam.gserviceaccount.com

      # Azure Container Registry (OIDC - Keyless Auth)
      # Required: All 5 inputs below
      # Setup: See docs/docker-ops.md "Azure OIDC Setup"
      # Note: IDs below are fake examples - replace with your actual Azure values
      acr_registry: myregistry.azurecr.io
      acr_repository: my-app
      azure_client_id: 12345678-90ab-cdef-1234-567890abcdef
      azure_tenant_id: 87654321-fedc-ba09-8765-4321fedcba09
      azure_subscription_id: a1b2c3d4-e5f6-7890-abcd-ef1234567890

      # Optional: Custom build settings
      dockerfile_path: ./Dockerfile
      build_platforms: linux/amd64,linux/arm64
      # Build args support placeholders: {{version}} = release version, {{branch}} = branch name
      build_args: APP_VERSION={{version}},BUILD_DATE={{branch}},ENV=production

    secrets:
      docker_token: ${{ secrets.DOCKER_TOKEN }}
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
# ===========================================================================
# Quick Reference
# ===========================================================================
#
# AI-Friendly Configuration:
#   - See Dependency & Permission Matrix in docs/docker-ops.md
#   - Matrix shows all mandatory inputs/secrets/roles per registry type
#   - Use AI Implementation Prompt template in docs for workflow generation
#
# Versioning:
#   - Auto-detected from package.json or GitVersion (ci/git-version.yml)
#   - No manual version input needed
#
# Placeholders in build_args:
#   - {{version}} = release version (e.g., 1.2.3)
#   - {{branch}} = current branch name (e.g., main, feature/xyz)
#   - Example: build_args: APP_VERSION={{version}},BRANCH={{branch}}
#
# Authentication Setup:
#   - DOCKER_TOKEN: Personal access token from https://hub.docker.com/settings/security
#   - GCP: Workload Identity Federation (keyless OIDC)
#     * Requires: id-token: write permission
#     * Service account needs: roles/artifactregistry.writer
#     * Setup guide: docs/docker-ops.md "GCP Workload Identity Federation Setup"
#   - Azure: OIDC with federated credentials (keyless)
#     * Requires: id-token: write permission
#     * Service principal needs: AcrPush role
#     * Security options: Strict (single branch) or Flexible (wildcard)
#     * Setup guide: docs/docker-ops.md "Azure OIDC Setup"
#   - SLACK_WEBHOOK_URL: Optional, from https://api.slack.com/messaging/webhooks
#
# Changelog:
#   - Create changes.md with version entries (### 1.2.0)
#   - Or auto-generated from git commits since last tag
#
# Full Documentation:
#   - See docs/docker-ops.md for complete setup guides, troubleshooting, and best practices
#   - AI Implementation Prompt template available for generating workflow configurations
