name: Docker Release Example

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  # ===========================================================================
  # Example 1: Minimal - GitHub Release Only
  # ===========================================================================
  # Creates GitHub release with SBOM. No external registries.

  # minimal:
  #   uses: udx/reusable-workflows/.github/workflows/docker-ops.yml@master
  #   with:
  #     image_name: my-app

  # ===========================================================================
  # Example 2: Docker Hub Publishing
  # ===========================================================================
  # Publishes to Docker Hub with version and latest tags

  # docker-hub:
  #   uses: udx/reusable-workflows/.github/workflows/docker-ops.yml@master
  #   with:
  #     image_name: my-app
  #     docker_login: myusername
  #     docker_org: myorg
  #     docker_repo: my-app
  #   secrets:
  #     docker_token: ${{ secrets.DOCKER_TOKEN }}

  # ===========================================================================
  # Example 3: Multi-Registry (Docker Hub + GCP + ACR + Slack)
  # ===========================================================================

  multi-registry:
    uses: udx/reusable-workflows/.github/workflows/docker-ops.yml@master
    with:
      image_name: my-app
      release_branch: main

      # Docker Hub
      docker_login: ${{ vars.DOCKER_USERNAME }}
      docker_org: myorg
      docker_repo: my-app

      # GCP Artifact Registry (Workload Identity Federation)
      gcp_region: us-central1
      gcp_project_id: my-gcp-project
      gcp_repo: docker-images
      gcp_workload_identity_provider: projects/123456789/locations/global/workloadIdentityPools/github/providers/github-provider
      gcp_service_account: github-actions@my-gcp-project.iam.gserviceaccount.com

      # Azure Container Registry
      acr_registry: myregistry.azurecr.io
      acr_repository: my-app

      # Optional: Custom build settings
      # dockerfile_path: ./Dockerfile
      # build_platforms: linux/amd64,linux/arm64
      # build_args: VERSION={{version}},ENV=production

    secrets:
      docker_token: ${{ secrets.DOCKER_TOKEN }}
      acr_credentials: ${{ secrets.ACR_CREDENTIALS }}
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
# ===========================================================================
# Quick Reference
# ===========================================================================
#
# Versioning:
#   - Auto-detected from package.json or GitVersion (ci/git-version.yml)
#
# Placeholders in build_args:
#   - {{version}} = release version
#   - {{branch}} = current branch name
#
# Secrets Setup:
#   - DOCKER_TOKEN: https://hub.docker.com/settings/security
#   - GCP: Uses Workload Identity Federation (keyless auth)
#     Setup: https://github.com/google-github-actions/auth#setup
#     Service account needs Artifact Registry Writer role
#   - ACR_CREDENTIALS: Service principal JSON with AcrPush role
#     Create with: az ad sp create-for-rbac --name "github-actions-acr" --role "AcrPush" --scopes /subscriptions/{sub-id}/resourceGroups/{rg}/providers/Microsoft.ContainerRegistry/registries/{registry} --sdk-auth
#   - SLACK_WEBHOOK_URL: https://api.slack.com/messaging/webhooks
#
# Changelog:
#   - Create changes.md with version entries (### 1.2.0)
#   - Or auto-generated from git commits
#
# See docs/docker-ops.md for full documentation
