name: Docker Release Example

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  # ===========================================================================
  # Docker Hub: docker-hub
  # USE CASE: Build, scan, and publish to Docker Hub + GitHub Releases
  # ===========================================================================
  docker-hub:
    uses: udx/reusable-workflows/.github/workflows/docker-ops.yml@master
    with:
      image_name: ${{ vars.IMAGE_NAME }}
      docker_login: ${{ vars.DOCKER_USERNAME }}
      docker_org: ${{ vars.DOCKER_ORG }}
      docker_repo: ${{ vars.DOCKER_REPO }}
    secrets:
      docker_token: ${{ secrets.DOCKER_TOKEN }}

  # ===========================================================================
  # GCP: gcr
  # USE CASE: Publish to GCP Artifact Registry using OIDC (Keyless)
  # ===========================================================================
  gcr:
    permissions:
      id-token: write
      contents: write
    uses: udx/reusable-workflows/.github/workflows/docker-ops.yml@master
    with:
      image_name: ${{ vars.IMAGE_NAME }}
      gcp_region: ${{ vars.GCP_REGION }}
      gcp_project_id: ${{ vars.GCP_PROJECT_ID }}
      gcp_repo: ${{ vars.GCP_REPO }}
      gcp_workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      gcp_service_account: ${{ vars.GCP_SERVICE_ACCOUNT }}

  # ===========================================================================
  # Azure: acr
  # USE CASE: Publish to Azure Container Registry using OIDC (Keyless)
  # ===========================================================================
  acr:
    permissions:
      id-token: write
      contents: write
    uses: udx/reusable-workflows/.github/workflows/docker-ops.yml@master
    with:
      image_name: ${{ vars.IMAGE_NAME }}
      acr_registry: ${{ vars.ACR_REGISTRY }}
      acr_repository: ${{ vars.ACR_REPOSITORY }}
      azure_client_id: ${{ vars.AZURE_CLIENT_ID }}
      azure_tenant_id: ${{ vars.AZURE_TENANT_ID }}
      azure_subscription_id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

  # ===========================================================================
  # All: all
  # USE CASE: Publish to Docker Hub, GCP, and Azure simultaneously
  # ===========================================================================
  all:
    permissions:
      id-token: write
      contents: write
    uses: udx/reusable-workflows/.github/workflows/docker-ops.yml@master
    with:
      image_name: ${{ vars.IMAGE_NAME }}
      # Docker Hub
      docker_login: ${{ vars.DOCKER_USERNAME }}
      docker_org: ${{ vars.DOCKER_ORG }}
      docker_repo: ${{ vars.DOCKER_REPO }}
      # GCP
      gcp_region: ${{ vars.GCP_REGION }}
      gcp_project_id: ${{ vars.GCP_PROJECT_ID }}
      gcp_repo: ${{ vars.GCP_REPO }}
      gcp_workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      gcp_service_account: ${{ vars.GCP_SERVICE_ACCOUNT }}
      # Azure
      acr_registry: ${{ vars.ACR_REGISTRY }}
      acr_repository: ${{ vars.ACR_REPOSITORY }}
      azure_client_id: ${{ vars.AZURE_CLIENT_ID }}
      azure_tenant_id: ${{ vars.AZURE_TENANT_ID }}
      azure_subscription_id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
    secrets:
      docker_token: ${{ secrets.DOCKER_TOKEN }}
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}

# Full Documentation:
#   - See docs/docker-ops.md for complete setup guides, troubleshooting, and best practices
