name: JS Ops Examples

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  # Verify-only example: runs on all pushes/PRs, never publishes GitHub Release.
  verify-only:
    permissions:
      contents: read
    uses: udx/reusable-workflows/.github/workflows/js-ops.yml@master
    with:
      release_branch: ""

  # Release example: release publishing enabled only on release branch pushes.
  release-branch-only:
    if: github.event_name == 'push' && github.ref_name == 'release'
    permissions:
      contents: write
    uses: udx/reusable-workflows/.github/workflows/js-ops.yml@master
    with:
      app_name: web-app
      working_directory: apps/web
      node_version: "24"
      package_manager: yarn
      release_branch: release
    secrets:
      gh_token: ${{ secrets.GH_TOKEN }}
