name: Release Package

on:
  push:
    branches:
      - latest

jobs:
  standard-release:
    permissions:
      contents: write
      id-token: write
    uses: udx/reusable-workflows/.github/workflows/npm-release-ops.yml@master
    with:
      node_version: "24"
      release_branch: "latest"
      provenance: "true"
      dist_dir: "dist"
      enable_gh_release: "true"
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
      gh_token: ${{ secrets.GH_TOKEN }}
