name: Publish WP Plugin Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g. 1.2.3a)'
        required: true
      version:
        description: 'Release version (e.g. 1.2.3), default: latest'
        required: false
      prerelease:
        description: 'Pre-release version (e.g. RC1, beta, etc...)'
        required: false

permissions:
  contents: write

jobs:
  release:
    uses: udx/reusable-workflows/.github/workflows/wp-gh-release-ops.yml@master
    with:
      tag: ${{ github.event.inputs.tag }}
      version: ${{ github.event.inputs.version }}
      prerelease: ${{ github.event.inputs.prerelease }}
